# Generated by Django 3.0.4 on 2020-03-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('icon', models.CharField(max_length=150, verbose_name='Icon')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
            ],
        ),
    ]
